<a href="https://colab.research.google.com/github/gitlogopolis/ciencia-de-datos/blob/main/6_Introducci%C3%B3n_a_la_librer%C3%ADa_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
valoraciones[0][1]

7

In [4]:
valoraciones[0,1]

7

In [5]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])

In [6]:
valoraciones2 #tres clientes, dos años, cuatro productos

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [7]:
valoraciones2[0,1,2]

5

In [8]:
np.zeros((3,2,4))  #Sirve para crear arreglos vacios

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
valoraciones2 + np.ones((3,2,4)) #Agrega un uno a cada elemento de la matriz valoraciones2

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [10]:
np.mean(valoraciones2) #Podemos consultar la media de la matriz

6.458333333333333

In [11]:
np.mean(valoraciones2, axis=0)   #Podemos obtener la media el eje 0 (Clientes)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [12]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))  #Permite convertir una lista en las dimensiones que se deseen

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
np.random.rand(2,2)  #Permite generar objetos aleatorios

array([[0.52885905, 0.59995407],
       [0.681411  , 0.17621623]])