In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/FERNANDO LOPEZ/Documents/base_datos_2008.csv", nrows = 100000) #Número de filas de archivo a leer.

In [2]:
x = df["ArrDelay"].dropna()

In [3]:
#Sacar Cuartiles
Q1 = np.percentile(x,25)
Q3 = np.percentile(x,75)
rangointer = Q3 - Q1 #Rango intercuartilico

In [4]:
umbralsuperior = Q3 + 1.5*rangointer
umbralinferior = Q1 - 1.5*rangointer

In [5]:
umbralsuperior

38.5

In [6]:
umbralinferior

-37.5

In [7]:
np.mean(x>umbralsuperior)

0.08387201361729721

In [8]:
np.mean(x<umbralinferior)

0.0019048005025431114

In [9]:
from sklearn.covariance import EllipticEnvelope

In [10]:
outliers = EllipticEnvelope(contamination = 0.01) #Crea un modelo que selecciona el 1% de datos que considere que esta muy alejado

In [11]:
var_list = ["DepDelay","TaxiIn","TaxiOut","CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay"]

In [12]:
x = np.array(df.loc[:,var_list].dropna())


In [13]:
outliers.fit(x)


EllipticEnvelope(contamination=0.01)

In [14]:
pred = outliers.predict(x)


In [15]:
pred  # pred ES UN ARRAY DE 1's

array([1, 1, 1, ..., 1, 1, 1])

In [19]:
elips_outliers = np.where(pred == -1)[0] 

In [20]:
elips_outliers #MUESTRA TODAS LAS VARIABLES QUE ESTAN MUY ALEJADAS

array([  444,  1161,  1188,  1191,  1412,  1418,  1503,  1634,  1911,
        1914,  2005,  2082,  2120,  2123,  2145,  2539,  2612,  2613,
        2725,  2771,  2937,  3120,  3589,  4146,  4265,  4430,  4437,
        4488,  4512,  4621,  4676,  4725,  5772,  5996,  5997,  6329,
        6358,  6515,  7245,  7257,  7460,  7480,  7481,  7620,  7698,
        7701,  7702,  7703,  7707,  7715,  8098,  8130,  8267,  8294,
        8298,  8327,  8484,  8566,  8683,  8691,  8865,  8993,  9922,
       10216, 10250, 10280, 10469, 10618, 10681, 10720, 10910, 11021,
       11231, 11237, 11242, 11316, 11955, 12085, 12088, 12240, 12452,
       12513, 12607, 12700, 12905, 12927, 12934, 13275, 13276, 13278,
       14259, 14282, 14285, 14297, 14318, 14358, 14367, 14510, 14544,
       14557, 14558, 14647, 14658, 14785, 14789, 14792, 14831, 14858,
       14870, 14871, 14880, 14881, 14940, 14945, 14946, 14947, 14948,
       14988, 15008, 15009, 15029, 15086, 15150, 15192, 15195, 15196,
       15197, 15202,

In [21]:
elips_outliers

array([  444,  1161,  1188,  1191,  1412,  1418,  1503,  1634,  1911,
        1914,  2005,  2082,  2120,  2123,  2145,  2539,  2612,  2613,
        2725,  2771,  2937,  3120,  3589,  4146,  4265,  4430,  4437,
        4488,  4512,  4621,  4676,  4725,  5772,  5996,  5997,  6329,
        6358,  6515,  7245,  7257,  7460,  7480,  7481,  7620,  7698,
        7701,  7702,  7703,  7707,  7715,  8098,  8130,  8267,  8294,
        8298,  8327,  8484,  8566,  8683,  8691,  8865,  8993,  9922,
       10216, 10250, 10280, 10469, 10618, 10681, 10720, 10910, 11021,
       11231, 11237, 11242, 11316, 11955, 12085, 12088, 12240, 12452,
       12513, 12607, 12700, 12905, 12927, 12934, 13275, 13276, 13278,
       14259, 14282, 14285, 14297, 14318, 14358, 14367, 14510, 14544,
       14557, 14558, 14647, 14658, 14785, 14789, 14792, 14831, 14858,
       14870, 14871, 14880, 14881, 14940, 14945, 14946, 14947, 14948,
       14988, 15008, 15009, 15029, 15086, 15150, 15192, 15195, 15196,
       15197, 15202,